# Generated by Django 5.2.1 on 2025-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('abertura', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('porte', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('cnae_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('cnae_principal_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('cnaes_secundarios', models.TextField(blank=True, null=True)),
                ('socios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CNAE',
                'managed': False,
            },
        ),
    ]
