# Generated by Django 5.2.1 on 2025-06-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
    ]
