# Generated by Django 5.2.1 on 2025-06-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0002_alter_empresa_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='abertura',
            new_name='data_abertura',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='cnae_principal_desc',
            new_name='descricao_cnae_principal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='porte',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='tipo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='porte_empresa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='situacao_cadastral',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_unidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='uf',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterModelTable(
            name='empresa',
            table=None,
        ),
    ]
